// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMHTWARKeVSGBLaYK_OHYX3bNLTpt_wE',
    appId: '1:880721351348:web:57e44e32f72b4d40867de1',
    messagingSenderId: '880721351348',
    projectId: 'echo-chat-app-97bf0',
    authDomain: 'echo-chat-app-97bf0.firebaseapp.com',
    storageBucket: 'echo-chat-app-97bf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKW5-BkaciPYuax3Rv21zItLA0qWNA368',
    appId: '1:880721351348:android:d3bf39fa9c225a76867de1',
    messagingSenderId: '880721351348',
    projectId: 'echo-chat-app-97bf0',
    storageBucket: 'echo-chat-app-97bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1JG_0sjVG4g8kLJXVazfgbCoYodO2JMQ',
    appId: '1:880721351348:ios:aa9e30c9325cee3f867de1',
    messagingSenderId: '880721351348',
    projectId: 'echo-chat-app-97bf0',
    storageBucket: 'echo-chat-app-97bf0.appspot.com',
    iosBundleId: 'com.example.echo',
  );
}
